spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  cache:
    jcache:
      config: classpath:ehcache.xml
  application:
    name: beer-service
  artemis:
    password: simetraehcapa
    user: artemis
  datasource:
    initialization-mode: EMBEDDED
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
  zipkin:
    enabled: false
sfg:
  brewery:
    inventory-user: good
    beer-inventory-service-host: http://localhost:8082
    inventory-password: beer
logging:
  level:
    guru:
      springframework: debug
