spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      data-source-properties:
        maintainTimeStats: 'false'
        useServerPrepStmts: 'true'
        cacheResultSetMetadata: 'true'
        cacheServerConfiguration: 'true'
        cachePrepStmts: 'true'
        rewriteBatchedStatements: 'true'
        prepStmtCacheSqlLimit: '2048'
        elideSetAutoCommits: 'true'
        useLocalSessionState: 'true'
        prepStmtCacheSize: '250'
      maximum-pool-size: '5'
    password: password
    username: beer_service
    url: jdbc:mysql://127.0.0.1:3306/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  cloud:
    discovery:
      enabled: 'false'
